// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: content.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "content.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace content {

namespace {

const ::google::protobuf::Descriptor* ContentData_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ContentData_reflection_ = NULL;
const ::google::protobuf::Descriptor* ContentPart_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ContentPart_reflection_ = NULL;
const ::google::protobuf::Descriptor* Content_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Content_reflection_ = NULL;
const ::google::protobuf::Descriptor* CmdResponse_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CmdResponse_reflection_ = NULL;
const ::google::protobuf::Descriptor* UpdatePart_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  UpdatePart_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_content_2eproto() {
  protobuf_AddDesc_content_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "content.proto");
  GOOGLE_CHECK(file != NULL);
  ContentData_descriptor_ = file->message_type(0);
  static const int ContentData_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ContentData, id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ContentData, title_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ContentData, authors_),
  };
  ContentData_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      ContentData_descriptor_,
      ContentData::default_instance_,
      ContentData_offsets_,
      -1,
      -1,
      -1,
      sizeof(ContentData),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ContentData, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ContentData, _is_default_instance_));
  ContentPart_descriptor_ = file->message_type(1);
  static const int ContentPart_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ContentPart, info_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ContentPart, format_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ContentPart, data_),
  };
  ContentPart_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      ContentPart_descriptor_,
      ContentPart::default_instance_,
      ContentPart_offsets_,
      -1,
      -1,
      -1,
      sizeof(ContentPart),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ContentPart, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ContentPart, _is_default_instance_));
  Content_descriptor_ = file->message_type(2);
  static const int Content_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Content, info_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Content, parts_),
  };
  Content_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      Content_descriptor_,
      Content::default_instance_,
      Content_offsets_,
      -1,
      -1,
      -1,
      sizeof(Content),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Content, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Content, _is_default_instance_));
  CmdResponse_descriptor_ = file->message_type(3);
  static const int CmdResponse_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CmdResponse, path_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CmdResponse, level_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CmdResponse, msg_),
  };
  CmdResponse_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      CmdResponse_descriptor_,
      CmdResponse::default_instance_,
      CmdResponse_offsets_,
      -1,
      -1,
      -1,
      sizeof(CmdResponse),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CmdResponse, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CmdResponse, _is_default_instance_));
  UpdatePart_descriptor_ = file->message_type(4);
  static const int UpdatePart_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UpdatePart, part_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UpdatePart, position_),
  };
  UpdatePart_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      UpdatePart_descriptor_,
      UpdatePart::default_instance_,
      UpdatePart_offsets_,
      -1,
      -1,
      -1,
      sizeof(UpdatePart),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UpdatePart, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UpdatePart, _is_default_instance_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_content_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      ContentData_descriptor_, &ContentData::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      ContentPart_descriptor_, &ContentPart::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      Content_descriptor_, &Content::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      CmdResponse_descriptor_, &CmdResponse::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      UpdatePart_descriptor_, &UpdatePart::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_content_2eproto() {
  delete ContentData::default_instance_;
  delete ContentData_reflection_;
  delete ContentPart::default_instance_;
  delete ContentPart_reflection_;
  delete Content::default_instance_;
  delete Content_reflection_;
  delete CmdResponse::default_instance_;
  delete CmdResponse_reflection_;
  delete UpdatePart::default_instance_;
  delete UpdatePart_reflection_;
}

void protobuf_AddDesc_content_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::common::protobuf_AddDesc_base_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\rcontent.proto\022\007content\032\nbase.proto\"U\n\013"
    "ContentData\022\030\n\002id\030\001 \001(\0132\014.common.Uuid\022\r\n"
    "\005title\030\002 \001(\t\022\035\n\007authors\030\003 \003(\0132\014.common.U"
    "uid\"_\n\013ContentPart\022\"\n\004info\030\001 \001(\0132\024.conte"
    "nt.ContentData\022\036\n\006format\030\002 \001(\0162\016.common."
    "Format\022\014\n\004data\030\003 \001(\t\"R\n\007Content\022\"\n\004info\030"
    "\001 \001(\0132\024.content.ContentData\022#\n\005parts\030\002 \003"
    "(\0132\024.content.ContentPart\"F\n\013CmdResponse\022"
    "\014\n\004path\030\001 \001(\t\022\034\n\005level\030\002 \001(\0162\r.common.Le"
    "vel\022\013\n\003msg\030\003 \001(\t\"B\n\nUpdatePart\022\"\n\004part\030\001"
    " \001(\0132\024.content.ContentPart\022\020\n\010position\030\002"
    " \001(\r2\344\001\n\021ContentCmdHandler\0220\n\004save\022\020.con"
    "tent.Content\032\024.content.CmdResponse\"\000\022.\n\006"
    "remove\022\014.common.Uuid\032\024.content.CmdRespon"
    "se\"\000\0222\n\nremovePart\022\014.common.Uuid\032\024.conte"
    "nt.CmdResponse\"\000\0229\n\nupdatePart\022\023.content"
    ".UpdatePart\032\024.content.CmdResponse\"\000B\003\370\001\001"
    "b\006proto3", 688);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "content.proto", &protobuf_RegisterTypes);
  ContentData::default_instance_ = new ContentData();
  ContentPart::default_instance_ = new ContentPart();
  Content::default_instance_ = new Content();
  CmdResponse::default_instance_ = new CmdResponse();
  UpdatePart::default_instance_ = new UpdatePart();
  ContentData::default_instance_->InitAsDefaultInstance();
  ContentPart::default_instance_->InitAsDefaultInstance();
  Content::default_instance_->InitAsDefaultInstance();
  CmdResponse::default_instance_->InitAsDefaultInstance();
  UpdatePart::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_content_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_content_2eproto {
  StaticDescriptorInitializer_content_2eproto() {
    protobuf_AddDesc_content_2eproto();
  }
} static_descriptor_initializer_content_2eproto_;

namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD;
static void MergeFromFail(int line) {
  GOOGLE_CHECK(false) << __FILE__ << ":" << line;
}

}  // namespace


// ===================================================================

void ContentData::_slow_mutable_id() {
  id_ = ::google::protobuf::Arena::CreateMessage< ::common::Uuid >(
        GetArenaNoVirtual());
}
::common::Uuid* ContentData::_slow_release_id() {
  if (id_ == NULL) {
    return NULL;
  } else {
    ::common::Uuid* temp = new ::common::Uuid;
    temp->MergeFrom(*id_);
    id_ = NULL;
    return temp;
  }
}
::common::Uuid* ContentData::unsafe_arena_release_id() {
  
  ::common::Uuid* temp = id_;
  id_ = NULL;
  return temp;
}
void ContentData::_slow_set_allocated_id(
    ::google::protobuf::Arena* message_arena, ::common::Uuid** id) {
    if (message_arena != NULL && 
        ::google::protobuf::Arena::GetArena(*id) == NULL) {
      message_arena->Own(*id);
    } else if (message_arena !=
               ::google::protobuf::Arena::GetArena(*id)) {
      ::common::Uuid* new_id = 
            ::google::protobuf::Arena::CreateMessage< ::common::Uuid >(
            message_arena);
      new_id->CopyFrom(**id);
      *id = new_id;
    }
}
void ContentData::unsafe_arena_set_allocated_id(
    ::common::Uuid* id) {
  if (GetArenaNoVirtual() == NULL) {
    delete id_;
  }
  id_ = id;
  if (id) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:content.ContentData.id)
}
#ifndef _MSC_VER
const int ContentData::kIdFieldNumber;
const int ContentData::kTitleFieldNumber;
const int ContentData::kAuthorsFieldNumber;
#endif  // !_MSC_VER

ContentData::ContentData()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:content.ContentData)
}

ContentData::ContentData(::google::protobuf::Arena* arena)
  : ::google::protobuf::Message(),
  _internal_metadata_(arena),
  authors_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:content.ContentData)
}

void ContentData::InitAsDefaultInstance() {
  _is_default_instance_ = true;
  id_ = const_cast< ::common::Uuid*>(&::common::Uuid::default_instance());
}

ContentData::ContentData(const ContentData& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:content.ContentData)
}

void ContentData::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  id_ = NULL;
  title_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

ContentData::~ContentData() {
  // @@protoc_insertion_point(destructor:content.ContentData)
  SharedDtor();
}

void ContentData::SharedDtor() {
  if (GetArenaNoVirtual() != NULL) {
    return;
  }

  title_.Destroy(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
  if (this != default_instance_) {
    delete id_;
  }
}

void ContentData::ArenaDtor(void* object) {
  ContentData* _this = reinterpret_cast< ContentData* >(object);
  (void)_this;
}
void ContentData::RegisterArenaDtor(::google::protobuf::Arena* arena) {
}
void ContentData::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ContentData::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ContentData_descriptor_;
}

const ContentData& ContentData::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_content_2eproto();
  return *default_instance_;
}

ContentData* ContentData::default_instance_ = NULL;

ContentData* ContentData::New(::google::protobuf::Arena* arena) const {
  return ::google::protobuf::Arena::CreateMessage<ContentData>(arena);
}

void ContentData::Clear() {
  if (GetArenaNoVirtual() == NULL && id_ != NULL) delete id_;
  id_ = NULL;
  title_.ClearToEmpty(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
  authors_.Clear();
}

bool ContentData::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:content.ContentData)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .common.Uuid id = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_id()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_title;
        break;
      }

      // optional string title = 2;
      case 2: {
        if (tag == 18) {
         parse_title:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_title()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->title().data(), this->title().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "content.ContentData.title");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_authors;
        break;
      }

      // repeated .common.Uuid authors = 3;
      case 3: {
        if (tag == 26) {
         parse_authors:
          DO_(input->IncrementRecursionDepth());
         parse_loop_authors:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_authors()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_loop_authors;
        input->UnsafeDecrementRecursionDepth();
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:content.ContentData)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:content.ContentData)
  return false;
#undef DO_
}

void ContentData::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:content.ContentData)
  // optional .common.Uuid id = 1;
  if (this->has_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, *this->id_, output);
  }

  // optional string title = 2;
  if (this->title().size() > 0) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->title().data(), this->title().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "content.ContentData.title");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->title(), output);
  }

  // repeated .common.Uuid authors = 3;
  for (unsigned int i = 0, n = this->authors_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, this->authors(i), output);
  }

  // @@protoc_insertion_point(serialize_end:content.ContentData)
}

::google::protobuf::uint8* ContentData::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:content.ContentData)
  // optional .common.Uuid id = 1;
  if (this->has_id()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, *this->id_, target);
  }

  // optional string title = 2;
  if (this->title().size() > 0) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->title().data(), this->title().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "content.ContentData.title");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->title(), target);
  }

  // repeated .common.Uuid authors = 3;
  for (unsigned int i = 0, n = this->authors_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        3, this->authors(i), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:content.ContentData)
  return target;
}

int ContentData::ByteSize() const {
  int total_size = 0;

  // optional .common.Uuid id = 1;
  if (this->has_id()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->id_);
  }

  // optional string title = 2;
  if (this->title().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->title());
  }

  // repeated .common.Uuid authors = 3;
  total_size += 1 * this->authors_size();
  for (int i = 0; i < this->authors_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->authors(i));
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ContentData::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const ContentData* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const ContentData>(
          &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void ContentData::MergeFrom(const ContentData& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  authors_.MergeFrom(from.authors_);
  if (from.has_id()) {
    mutable_id()->::common::Uuid::MergeFrom(from.id());
  }
  if (from.title().size() > 0) {
    set_title(from.title());
  }
}

void ContentData::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ContentData::CopyFrom(const ContentData& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ContentData::IsInitialized() const {

  return true;
}

void ContentData::Swap(ContentData* other) {
  if (other == this) return;
  if (GetArenaNoVirtual() == other->GetArenaNoVirtual()) {
    InternalSwap(other);
  } else {
    ContentData temp;
    temp.MergeFrom(*this);
    CopyFrom(*other);
    other->CopyFrom(temp);
  }
}
void ContentData::UnsafeArenaSwap(ContentData* other) {
  if (other == this) return;
  GOOGLE_DCHECK(GetArenaNoVirtual() == other->GetArenaNoVirtual());
  InternalSwap(other);
}
void ContentData::InternalSwap(ContentData* other) {
  std::swap(id_, other->id_);
  title_.Swap(&other->title_);
  authors_.UnsafeArenaSwap(&other->authors_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata ContentData::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ContentData_descriptor_;
  metadata.reflection = ContentData_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// ContentData

// optional .common.Uuid id = 1;
bool ContentData::has_id() const {
  return !_is_default_instance_ && id_ != NULL;
}
void ContentData::clear_id() {
  if (GetArenaNoVirtual() == NULL && id_ != NULL) delete id_;
  id_ = NULL;
}
 const ::common::Uuid& ContentData::id() const {
  // @@protoc_insertion_point(field_get:content.ContentData.id)
  return id_ != NULL ? *id_ : *default_instance_->id_;
}
 ::common::Uuid* ContentData::mutable_id() {
  
  if (id_ == NULL) {
    _slow_mutable_id();  }
  // @@protoc_insertion_point(field_mutable:content.ContentData.id)
  return id_;
}
 ::common::Uuid* ContentData::release_id() {
  
  if (GetArenaNoVirtual() != NULL) {
    return _slow_release_id();
  } else {
    ::common::Uuid* temp = id_;
    id_ = NULL;
    return temp;
  }
}
 void ContentData::set_allocated_id(::common::Uuid* id) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete id_;
  }
  if (id != NULL) {
    _slow_set_allocated_id(message_arena, &id);
  }
  id_ = id;
  if (id) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:content.ContentData.id)
}

// optional string title = 2;
void ContentData::clear_title() {
  title_.ClearToEmpty(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
 const ::std::string& ContentData::title() const {
  // @@protoc_insertion_point(field_get:content.ContentData.title)
  return title_.Get(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void ContentData::set_title(const ::std::string& value) {
  
  title_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value, GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set:content.ContentData.title)
}
 void ContentData::set_title(const char* value) {
  
  title_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_char:content.ContentData.title)
}
 void ContentData::set_title(const char* value,
    size_t size) {
  
  title_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_pointer:content.ContentData.title)
}
 ::std::string* ContentData::mutable_title() {
  
  // @@protoc_insertion_point(field_mutable:content.ContentData.title)
  return title_.Mutable(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
 ::std::string* ContentData::release_title() {
  
  return title_.Release(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
 ::std::string* ContentData::unsafe_arena_release_title() {
  GOOGLE_DCHECK(GetArenaNoVirtual() != NULL);
  
  return title_.UnsafeArenaRelease(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      GetArenaNoVirtual());
}
 void ContentData::set_allocated_title(::std::string* title) {
  if (title != NULL) {
    
  } else {
    
  }
  title_.SetAllocated(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), title,
      GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_allocated:content.ContentData.title)
}
 void ContentData::unsafe_arena_set_allocated_title(
    ::std::string* title) {
  GOOGLE_DCHECK(GetArenaNoVirtual() != NULL);
  if (title != NULL) {
    
  } else {
    
  }
  title_.UnsafeArenaSetAllocated(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      title, GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_allocated:content.ContentData.title)
}

// repeated .common.Uuid authors = 3;
int ContentData::authors_size() const {
  return authors_.size();
}
void ContentData::clear_authors() {
  authors_.Clear();
}
 const ::common::Uuid& ContentData::authors(int index) const {
  // @@protoc_insertion_point(field_get:content.ContentData.authors)
  return authors_.Get(index);
}
 ::common::Uuid* ContentData::mutable_authors(int index) {
  // @@protoc_insertion_point(field_mutable:content.ContentData.authors)
  return authors_.Mutable(index);
}
 ::common::Uuid* ContentData::add_authors() {
  // @@protoc_insertion_point(field_add:content.ContentData.authors)
  return authors_.Add();
}
 const ::google::protobuf::RepeatedPtrField< ::common::Uuid >&
ContentData::authors() const {
  // @@protoc_insertion_point(field_list:content.ContentData.authors)
  return authors_;
}
 ::google::protobuf::RepeatedPtrField< ::common::Uuid >*
ContentData::mutable_authors() {
  // @@protoc_insertion_point(field_mutable_list:content.ContentData.authors)
  return &authors_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

void ContentPart::_slow_mutable_info() {
  info_ = ::google::protobuf::Arena::CreateMessage< ::content::ContentData >(
        GetArenaNoVirtual());
}
::content::ContentData* ContentPart::_slow_release_info() {
  if (info_ == NULL) {
    return NULL;
  } else {
    ::content::ContentData* temp = new ::content::ContentData;
    temp->MergeFrom(*info_);
    info_ = NULL;
    return temp;
  }
}
::content::ContentData* ContentPart::unsafe_arena_release_info() {
  
  ::content::ContentData* temp = info_;
  info_ = NULL;
  return temp;
}
void ContentPart::_slow_set_allocated_info(
    ::google::protobuf::Arena* message_arena, ::content::ContentData** info) {
    if (message_arena != NULL && 
        ::google::protobuf::Arena::GetArena(*info) == NULL) {
      message_arena->Own(*info);
    } else if (message_arena !=
               ::google::protobuf::Arena::GetArena(*info)) {
      ::content::ContentData* new_info = 
            ::google::protobuf::Arena::CreateMessage< ::content::ContentData >(
            message_arena);
      new_info->CopyFrom(**info);
      *info = new_info;
    }
}
void ContentPart::unsafe_arena_set_allocated_info(
    ::content::ContentData* info) {
  if (GetArenaNoVirtual() == NULL) {
    delete info_;
  }
  info_ = info;
  if (info) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:content.ContentPart.info)
}
#ifndef _MSC_VER
const int ContentPart::kInfoFieldNumber;
const int ContentPart::kFormatFieldNumber;
const int ContentPart::kDataFieldNumber;
#endif  // !_MSC_VER

ContentPart::ContentPart()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:content.ContentPart)
}

ContentPart::ContentPart(::google::protobuf::Arena* arena)
  : ::google::protobuf::Message(),
  _internal_metadata_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:content.ContentPart)
}

void ContentPart::InitAsDefaultInstance() {
  _is_default_instance_ = true;
  info_ = const_cast< ::content::ContentData*>(&::content::ContentData::default_instance());
}

ContentPart::ContentPart(const ContentPart& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:content.ContentPart)
}

void ContentPart::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  info_ = NULL;
  format_ = 0;
  data_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

ContentPart::~ContentPart() {
  // @@protoc_insertion_point(destructor:content.ContentPart)
  SharedDtor();
}

void ContentPart::SharedDtor() {
  if (GetArenaNoVirtual() != NULL) {
    return;
  }

  data_.Destroy(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
  if (this != default_instance_) {
    delete info_;
  }
}

void ContentPart::ArenaDtor(void* object) {
  ContentPart* _this = reinterpret_cast< ContentPart* >(object);
  (void)_this;
}
void ContentPart::RegisterArenaDtor(::google::protobuf::Arena* arena) {
}
void ContentPart::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ContentPart::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ContentPart_descriptor_;
}

const ContentPart& ContentPart::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_content_2eproto();
  return *default_instance_;
}

ContentPart* ContentPart::default_instance_ = NULL;

ContentPart* ContentPart::New(::google::protobuf::Arena* arena) const {
  return ::google::protobuf::Arena::CreateMessage<ContentPart>(arena);
}

void ContentPart::Clear() {
  if (GetArenaNoVirtual() == NULL && info_ != NULL) delete info_;
  info_ = NULL;
  format_ = 0;
  data_.ClearToEmpty(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}

bool ContentPart::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:content.ContentPart)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .content.ContentData info = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_info()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_format;
        break;
      }

      // optional .common.Format format = 2;
      case 2: {
        if (tag == 16) {
         parse_format:
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_format(static_cast< ::common::Format >(value));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_data;
        break;
      }

      // optional string data = 3;
      case 3: {
        if (tag == 26) {
         parse_data:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_data()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->data().data(), this->data().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "content.ContentPart.data");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:content.ContentPart)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:content.ContentPart)
  return false;
#undef DO_
}

void ContentPart::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:content.ContentPart)
  // optional .content.ContentData info = 1;
  if (this->has_info()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, *this->info_, output);
  }

  // optional .common.Format format = 2;
  if (this->format() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      2, this->format(), output);
  }

  // optional string data = 3;
  if (this->data().size() > 0) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->data().data(), this->data().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "content.ContentPart.data");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->data(), output);
  }

  // @@protoc_insertion_point(serialize_end:content.ContentPart)
}

::google::protobuf::uint8* ContentPart::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:content.ContentPart)
  // optional .content.ContentData info = 1;
  if (this->has_info()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, *this->info_, target);
  }

  // optional .common.Format format = 2;
  if (this->format() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      2, this->format(), target);
  }

  // optional string data = 3;
  if (this->data().size() > 0) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->data().data(), this->data().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "content.ContentPart.data");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->data(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:content.ContentPart)
  return target;
}

int ContentPart::ByteSize() const {
  int total_size = 0;

  // optional .content.ContentData info = 1;
  if (this->has_info()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->info_);
  }

  // optional .common.Format format = 2;
  if (this->format() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->format());
  }

  // optional string data = 3;
  if (this->data().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->data());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ContentPart::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const ContentPart* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const ContentPart>(
          &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void ContentPart::MergeFrom(const ContentPart& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from.has_info()) {
    mutable_info()->::content::ContentData::MergeFrom(from.info());
  }
  if (from.format() != 0) {
    set_format(from.format());
  }
  if (from.data().size() > 0) {
    set_data(from.data());
  }
}

void ContentPart::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ContentPart::CopyFrom(const ContentPart& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ContentPart::IsInitialized() const {

  return true;
}

void ContentPart::Swap(ContentPart* other) {
  if (other == this) return;
  if (GetArenaNoVirtual() == other->GetArenaNoVirtual()) {
    InternalSwap(other);
  } else {
    ContentPart temp;
    temp.MergeFrom(*this);
    CopyFrom(*other);
    other->CopyFrom(temp);
  }
}
void ContentPart::UnsafeArenaSwap(ContentPart* other) {
  if (other == this) return;
  GOOGLE_DCHECK(GetArenaNoVirtual() == other->GetArenaNoVirtual());
  InternalSwap(other);
}
void ContentPart::InternalSwap(ContentPart* other) {
  std::swap(info_, other->info_);
  std::swap(format_, other->format_);
  data_.Swap(&other->data_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata ContentPart::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ContentPart_descriptor_;
  metadata.reflection = ContentPart_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// ContentPart

// optional .content.ContentData info = 1;
bool ContentPart::has_info() const {
  return !_is_default_instance_ && info_ != NULL;
}
void ContentPart::clear_info() {
  if (GetArenaNoVirtual() == NULL && info_ != NULL) delete info_;
  info_ = NULL;
}
 const ::content::ContentData& ContentPart::info() const {
  // @@protoc_insertion_point(field_get:content.ContentPart.info)
  return info_ != NULL ? *info_ : *default_instance_->info_;
}
 ::content::ContentData* ContentPart::mutable_info() {
  
  if (info_ == NULL) {
    _slow_mutable_info();  }
  // @@protoc_insertion_point(field_mutable:content.ContentPart.info)
  return info_;
}
 ::content::ContentData* ContentPart::release_info() {
  
  if (GetArenaNoVirtual() != NULL) {
    return _slow_release_info();
  } else {
    ::content::ContentData* temp = info_;
    info_ = NULL;
    return temp;
  }
}
 void ContentPart::set_allocated_info(::content::ContentData* info) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete info_;
  }
  if (info != NULL) {
    _slow_set_allocated_info(message_arena, &info);
  }
  info_ = info;
  if (info) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:content.ContentPart.info)
}

// optional .common.Format format = 2;
void ContentPart::clear_format() {
  format_ = 0;
}
 ::common::Format ContentPart::format() const {
  // @@protoc_insertion_point(field_get:content.ContentPart.format)
  return static_cast< ::common::Format >(format_);
}
 void ContentPart::set_format(::common::Format value) {
  
  format_ = value;
  // @@protoc_insertion_point(field_set:content.ContentPart.format)
}

// optional string data = 3;
void ContentPart::clear_data() {
  data_.ClearToEmpty(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
 const ::std::string& ContentPart::data() const {
  // @@protoc_insertion_point(field_get:content.ContentPart.data)
  return data_.Get(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void ContentPart::set_data(const ::std::string& value) {
  
  data_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value, GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set:content.ContentPart.data)
}
 void ContentPart::set_data(const char* value) {
  
  data_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_char:content.ContentPart.data)
}
 void ContentPart::set_data(const char* value,
    size_t size) {
  
  data_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_pointer:content.ContentPart.data)
}
 ::std::string* ContentPart::mutable_data() {
  
  // @@protoc_insertion_point(field_mutable:content.ContentPart.data)
  return data_.Mutable(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
 ::std::string* ContentPart::release_data() {
  
  return data_.Release(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
 ::std::string* ContentPart::unsafe_arena_release_data() {
  GOOGLE_DCHECK(GetArenaNoVirtual() != NULL);
  
  return data_.UnsafeArenaRelease(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      GetArenaNoVirtual());
}
 void ContentPart::set_allocated_data(::std::string* data) {
  if (data != NULL) {
    
  } else {
    
  }
  data_.SetAllocated(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), data,
      GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_allocated:content.ContentPart.data)
}
 void ContentPart::unsafe_arena_set_allocated_data(
    ::std::string* data) {
  GOOGLE_DCHECK(GetArenaNoVirtual() != NULL);
  if (data != NULL) {
    
  } else {
    
  }
  data_.UnsafeArenaSetAllocated(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      data, GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_allocated:content.ContentPart.data)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

void Content::_slow_mutable_info() {
  info_ = ::google::protobuf::Arena::CreateMessage< ::content::ContentData >(
        GetArenaNoVirtual());
}
::content::ContentData* Content::_slow_release_info() {
  if (info_ == NULL) {
    return NULL;
  } else {
    ::content::ContentData* temp = new ::content::ContentData;
    temp->MergeFrom(*info_);
    info_ = NULL;
    return temp;
  }
}
::content::ContentData* Content::unsafe_arena_release_info() {
  
  ::content::ContentData* temp = info_;
  info_ = NULL;
  return temp;
}
void Content::_slow_set_allocated_info(
    ::google::protobuf::Arena* message_arena, ::content::ContentData** info) {
    if (message_arena != NULL && 
        ::google::protobuf::Arena::GetArena(*info) == NULL) {
      message_arena->Own(*info);
    } else if (message_arena !=
               ::google::protobuf::Arena::GetArena(*info)) {
      ::content::ContentData* new_info = 
            ::google::protobuf::Arena::CreateMessage< ::content::ContentData >(
            message_arena);
      new_info->CopyFrom(**info);
      *info = new_info;
    }
}
void Content::unsafe_arena_set_allocated_info(
    ::content::ContentData* info) {
  if (GetArenaNoVirtual() == NULL) {
    delete info_;
  }
  info_ = info;
  if (info) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:content.Content.info)
}
#ifndef _MSC_VER
const int Content::kInfoFieldNumber;
const int Content::kPartsFieldNumber;
#endif  // !_MSC_VER

Content::Content()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:content.Content)
}

Content::Content(::google::protobuf::Arena* arena)
  : ::google::protobuf::Message(),
  _internal_metadata_(arena),
  parts_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:content.Content)
}

void Content::InitAsDefaultInstance() {
  _is_default_instance_ = true;
  info_ = const_cast< ::content::ContentData*>(&::content::ContentData::default_instance());
}

Content::Content(const Content& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:content.Content)
}

void Content::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  info_ = NULL;
}

Content::~Content() {
  // @@protoc_insertion_point(destructor:content.Content)
  SharedDtor();
}

void Content::SharedDtor() {
  if (GetArenaNoVirtual() != NULL) {
    return;
  }

  if (this != default_instance_) {
    delete info_;
  }
}

void Content::ArenaDtor(void* object) {
  Content* _this = reinterpret_cast< Content* >(object);
  (void)_this;
}
void Content::RegisterArenaDtor(::google::protobuf::Arena* arena) {
}
void Content::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Content::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Content_descriptor_;
}

const Content& Content::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_content_2eproto();
  return *default_instance_;
}

Content* Content::default_instance_ = NULL;

Content* Content::New(::google::protobuf::Arena* arena) const {
  return ::google::protobuf::Arena::CreateMessage<Content>(arena);
}

void Content::Clear() {
  if (GetArenaNoVirtual() == NULL && info_ != NULL) delete info_;
  info_ = NULL;
  parts_.Clear();
}

bool Content::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:content.Content)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .content.ContentData info = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_info()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_parts;
        break;
      }

      // repeated .content.ContentPart parts = 2;
      case 2: {
        if (tag == 18) {
         parse_parts:
          DO_(input->IncrementRecursionDepth());
         parse_loop_parts:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_parts()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_loop_parts;
        input->UnsafeDecrementRecursionDepth();
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:content.Content)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:content.Content)
  return false;
#undef DO_
}

void Content::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:content.Content)
  // optional .content.ContentData info = 1;
  if (this->has_info()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, *this->info_, output);
  }

  // repeated .content.ContentPart parts = 2;
  for (unsigned int i = 0, n = this->parts_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->parts(i), output);
  }

  // @@protoc_insertion_point(serialize_end:content.Content)
}

::google::protobuf::uint8* Content::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:content.Content)
  // optional .content.ContentData info = 1;
  if (this->has_info()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, *this->info_, target);
  }

  // repeated .content.ContentPart parts = 2;
  for (unsigned int i = 0, n = this->parts_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, this->parts(i), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:content.Content)
  return target;
}

int Content::ByteSize() const {
  int total_size = 0;

  // optional .content.ContentData info = 1;
  if (this->has_info()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->info_);
  }

  // repeated .content.ContentPart parts = 2;
  total_size += 1 * this->parts_size();
  for (int i = 0; i < this->parts_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->parts(i));
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Content::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const Content* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const Content>(
          &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Content::MergeFrom(const Content& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  parts_.MergeFrom(from.parts_);
  if (from.has_info()) {
    mutable_info()->::content::ContentData::MergeFrom(from.info());
  }
}

void Content::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Content::CopyFrom(const Content& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Content::IsInitialized() const {

  return true;
}

void Content::Swap(Content* other) {
  if (other == this) return;
  if (GetArenaNoVirtual() == other->GetArenaNoVirtual()) {
    InternalSwap(other);
  } else {
    Content temp;
    temp.MergeFrom(*this);
    CopyFrom(*other);
    other->CopyFrom(temp);
  }
}
void Content::UnsafeArenaSwap(Content* other) {
  if (other == this) return;
  GOOGLE_DCHECK(GetArenaNoVirtual() == other->GetArenaNoVirtual());
  InternalSwap(other);
}
void Content::InternalSwap(Content* other) {
  std::swap(info_, other->info_);
  parts_.UnsafeArenaSwap(&other->parts_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Content::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Content_descriptor_;
  metadata.reflection = Content_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Content

// optional .content.ContentData info = 1;
bool Content::has_info() const {
  return !_is_default_instance_ && info_ != NULL;
}
void Content::clear_info() {
  if (GetArenaNoVirtual() == NULL && info_ != NULL) delete info_;
  info_ = NULL;
}
 const ::content::ContentData& Content::info() const {
  // @@protoc_insertion_point(field_get:content.Content.info)
  return info_ != NULL ? *info_ : *default_instance_->info_;
}
 ::content::ContentData* Content::mutable_info() {
  
  if (info_ == NULL) {
    _slow_mutable_info();  }
  // @@protoc_insertion_point(field_mutable:content.Content.info)
  return info_;
}
 ::content::ContentData* Content::release_info() {
  
  if (GetArenaNoVirtual() != NULL) {
    return _slow_release_info();
  } else {
    ::content::ContentData* temp = info_;
    info_ = NULL;
    return temp;
  }
}
 void Content::set_allocated_info(::content::ContentData* info) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete info_;
  }
  if (info != NULL) {
    _slow_set_allocated_info(message_arena, &info);
  }
  info_ = info;
  if (info) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:content.Content.info)
}

// repeated .content.ContentPart parts = 2;
int Content::parts_size() const {
  return parts_.size();
}
void Content::clear_parts() {
  parts_.Clear();
}
 const ::content::ContentPart& Content::parts(int index) const {
  // @@protoc_insertion_point(field_get:content.Content.parts)
  return parts_.Get(index);
}
 ::content::ContentPart* Content::mutable_parts(int index) {
  // @@protoc_insertion_point(field_mutable:content.Content.parts)
  return parts_.Mutable(index);
}
 ::content::ContentPart* Content::add_parts() {
  // @@protoc_insertion_point(field_add:content.Content.parts)
  return parts_.Add();
}
 const ::google::protobuf::RepeatedPtrField< ::content::ContentPart >&
Content::parts() const {
  // @@protoc_insertion_point(field_list:content.Content.parts)
  return parts_;
}
 ::google::protobuf::RepeatedPtrField< ::content::ContentPart >*
Content::mutable_parts() {
  // @@protoc_insertion_point(field_mutable_list:content.Content.parts)
  return &parts_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#ifndef _MSC_VER
const int CmdResponse::kPathFieldNumber;
const int CmdResponse::kLevelFieldNumber;
const int CmdResponse::kMsgFieldNumber;
#endif  // !_MSC_VER

CmdResponse::CmdResponse()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:content.CmdResponse)
}

CmdResponse::CmdResponse(::google::protobuf::Arena* arena)
  : ::google::protobuf::Message(),
  _internal_metadata_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:content.CmdResponse)
}

void CmdResponse::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

CmdResponse::CmdResponse(const CmdResponse& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:content.CmdResponse)
}

void CmdResponse::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  path_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  level_ = 0;
  msg_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

CmdResponse::~CmdResponse() {
  // @@protoc_insertion_point(destructor:content.CmdResponse)
  SharedDtor();
}

void CmdResponse::SharedDtor() {
  if (GetArenaNoVirtual() != NULL) {
    return;
  }

  path_.Destroy(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
  msg_.Destroy(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
  if (this != default_instance_) {
  }
}

void CmdResponse::ArenaDtor(void* object) {
  CmdResponse* _this = reinterpret_cast< CmdResponse* >(object);
  (void)_this;
}
void CmdResponse::RegisterArenaDtor(::google::protobuf::Arena* arena) {
}
void CmdResponse::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CmdResponse::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CmdResponse_descriptor_;
}

const CmdResponse& CmdResponse::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_content_2eproto();
  return *default_instance_;
}

CmdResponse* CmdResponse::default_instance_ = NULL;

CmdResponse* CmdResponse::New(::google::protobuf::Arena* arena) const {
  return ::google::protobuf::Arena::CreateMessage<CmdResponse>(arena);
}

void CmdResponse::Clear() {
  path_.ClearToEmpty(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
  level_ = 0;
  msg_.ClearToEmpty(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}

bool CmdResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:content.CmdResponse)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string path = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_path()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->path().data(), this->path().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "content.CmdResponse.path");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_level;
        break;
      }

      // optional .common.Level level = 2;
      case 2: {
        if (tag == 16) {
         parse_level:
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_level(static_cast< ::common::Level >(value));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_msg;
        break;
      }

      // optional string msg = 3;
      case 3: {
        if (tag == 26) {
         parse_msg:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_msg()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->msg().data(), this->msg().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "content.CmdResponse.msg");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:content.CmdResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:content.CmdResponse)
  return false;
#undef DO_
}

void CmdResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:content.CmdResponse)
  // optional string path = 1;
  if (this->path().size() > 0) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->path().data(), this->path().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "content.CmdResponse.path");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->path(), output);
  }

  // optional .common.Level level = 2;
  if (this->level() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      2, this->level(), output);
  }

  // optional string msg = 3;
  if (this->msg().size() > 0) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->msg().data(), this->msg().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "content.CmdResponse.msg");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->msg(), output);
  }

  // @@protoc_insertion_point(serialize_end:content.CmdResponse)
}

::google::protobuf::uint8* CmdResponse::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:content.CmdResponse)
  // optional string path = 1;
  if (this->path().size() > 0) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->path().data(), this->path().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "content.CmdResponse.path");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->path(), target);
  }

  // optional .common.Level level = 2;
  if (this->level() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      2, this->level(), target);
  }

  // optional string msg = 3;
  if (this->msg().size() > 0) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->msg().data(), this->msg().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "content.CmdResponse.msg");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->msg(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:content.CmdResponse)
  return target;
}

int CmdResponse::ByteSize() const {
  int total_size = 0;

  // optional string path = 1;
  if (this->path().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->path());
  }

  // optional .common.Level level = 2;
  if (this->level() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->level());
  }

  // optional string msg = 3;
  if (this->msg().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->msg());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CmdResponse::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const CmdResponse* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const CmdResponse>(
          &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void CmdResponse::MergeFrom(const CmdResponse& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from.path().size() > 0) {
    set_path(from.path());
  }
  if (from.level() != 0) {
    set_level(from.level());
  }
  if (from.msg().size() > 0) {
    set_msg(from.msg());
  }
}

void CmdResponse::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CmdResponse::CopyFrom(const CmdResponse& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CmdResponse::IsInitialized() const {

  return true;
}

void CmdResponse::Swap(CmdResponse* other) {
  if (other == this) return;
  if (GetArenaNoVirtual() == other->GetArenaNoVirtual()) {
    InternalSwap(other);
  } else {
    CmdResponse temp;
    temp.MergeFrom(*this);
    CopyFrom(*other);
    other->CopyFrom(temp);
  }
}
void CmdResponse::UnsafeArenaSwap(CmdResponse* other) {
  if (other == this) return;
  GOOGLE_DCHECK(GetArenaNoVirtual() == other->GetArenaNoVirtual());
  InternalSwap(other);
}
void CmdResponse::InternalSwap(CmdResponse* other) {
  path_.Swap(&other->path_);
  std::swap(level_, other->level_);
  msg_.Swap(&other->msg_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata CmdResponse::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CmdResponse_descriptor_;
  metadata.reflection = CmdResponse_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// CmdResponse

// optional string path = 1;
void CmdResponse::clear_path() {
  path_.ClearToEmpty(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
 const ::std::string& CmdResponse::path() const {
  // @@protoc_insertion_point(field_get:content.CmdResponse.path)
  return path_.Get(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void CmdResponse::set_path(const ::std::string& value) {
  
  path_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value, GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set:content.CmdResponse.path)
}
 void CmdResponse::set_path(const char* value) {
  
  path_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_char:content.CmdResponse.path)
}
 void CmdResponse::set_path(const char* value,
    size_t size) {
  
  path_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_pointer:content.CmdResponse.path)
}
 ::std::string* CmdResponse::mutable_path() {
  
  // @@protoc_insertion_point(field_mutable:content.CmdResponse.path)
  return path_.Mutable(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
 ::std::string* CmdResponse::release_path() {
  
  return path_.Release(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
 ::std::string* CmdResponse::unsafe_arena_release_path() {
  GOOGLE_DCHECK(GetArenaNoVirtual() != NULL);
  
  return path_.UnsafeArenaRelease(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      GetArenaNoVirtual());
}
 void CmdResponse::set_allocated_path(::std::string* path) {
  if (path != NULL) {
    
  } else {
    
  }
  path_.SetAllocated(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), path,
      GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_allocated:content.CmdResponse.path)
}
 void CmdResponse::unsafe_arena_set_allocated_path(
    ::std::string* path) {
  GOOGLE_DCHECK(GetArenaNoVirtual() != NULL);
  if (path != NULL) {
    
  } else {
    
  }
  path_.UnsafeArenaSetAllocated(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      path, GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_allocated:content.CmdResponse.path)
}

// optional .common.Level level = 2;
void CmdResponse::clear_level() {
  level_ = 0;
}
 ::common::Level CmdResponse::level() const {
  // @@protoc_insertion_point(field_get:content.CmdResponse.level)
  return static_cast< ::common::Level >(level_);
}
 void CmdResponse::set_level(::common::Level value) {
  
  level_ = value;
  // @@protoc_insertion_point(field_set:content.CmdResponse.level)
}

// optional string msg = 3;
void CmdResponse::clear_msg() {
  msg_.ClearToEmpty(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
 const ::std::string& CmdResponse::msg() const {
  // @@protoc_insertion_point(field_get:content.CmdResponse.msg)
  return msg_.Get(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void CmdResponse::set_msg(const ::std::string& value) {
  
  msg_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value, GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set:content.CmdResponse.msg)
}
 void CmdResponse::set_msg(const char* value) {
  
  msg_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_char:content.CmdResponse.msg)
}
 void CmdResponse::set_msg(const char* value,
    size_t size) {
  
  msg_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_pointer:content.CmdResponse.msg)
}
 ::std::string* CmdResponse::mutable_msg() {
  
  // @@protoc_insertion_point(field_mutable:content.CmdResponse.msg)
  return msg_.Mutable(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
 ::std::string* CmdResponse::release_msg() {
  
  return msg_.Release(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
 ::std::string* CmdResponse::unsafe_arena_release_msg() {
  GOOGLE_DCHECK(GetArenaNoVirtual() != NULL);
  
  return msg_.UnsafeArenaRelease(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      GetArenaNoVirtual());
}
 void CmdResponse::set_allocated_msg(::std::string* msg) {
  if (msg != NULL) {
    
  } else {
    
  }
  msg_.SetAllocated(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), msg,
      GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_allocated:content.CmdResponse.msg)
}
 void CmdResponse::unsafe_arena_set_allocated_msg(
    ::std::string* msg) {
  GOOGLE_DCHECK(GetArenaNoVirtual() != NULL);
  if (msg != NULL) {
    
  } else {
    
  }
  msg_.UnsafeArenaSetAllocated(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      msg, GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_allocated:content.CmdResponse.msg)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

void UpdatePart::_slow_mutable_part() {
  part_ = ::google::protobuf::Arena::CreateMessage< ::content::ContentPart >(
        GetArenaNoVirtual());
}
::content::ContentPart* UpdatePart::_slow_release_part() {
  if (part_ == NULL) {
    return NULL;
  } else {
    ::content::ContentPart* temp = new ::content::ContentPart;
    temp->MergeFrom(*part_);
    part_ = NULL;
    return temp;
  }
}
::content::ContentPart* UpdatePart::unsafe_arena_release_part() {
  
  ::content::ContentPart* temp = part_;
  part_ = NULL;
  return temp;
}
void UpdatePart::_slow_set_allocated_part(
    ::google::protobuf::Arena* message_arena, ::content::ContentPart** part) {
    if (message_arena != NULL && 
        ::google::protobuf::Arena::GetArena(*part) == NULL) {
      message_arena->Own(*part);
    } else if (message_arena !=
               ::google::protobuf::Arena::GetArena(*part)) {
      ::content::ContentPart* new_part = 
            ::google::protobuf::Arena::CreateMessage< ::content::ContentPart >(
            message_arena);
      new_part->CopyFrom(**part);
      *part = new_part;
    }
}
void UpdatePart::unsafe_arena_set_allocated_part(
    ::content::ContentPart* part) {
  if (GetArenaNoVirtual() == NULL) {
    delete part_;
  }
  part_ = part;
  if (part) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:content.UpdatePart.part)
}
#ifndef _MSC_VER
const int UpdatePart::kPartFieldNumber;
const int UpdatePart::kPositionFieldNumber;
#endif  // !_MSC_VER

UpdatePart::UpdatePart()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:content.UpdatePart)
}

UpdatePart::UpdatePart(::google::protobuf::Arena* arena)
  : ::google::protobuf::Message(),
  _internal_metadata_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:content.UpdatePart)
}

void UpdatePart::InitAsDefaultInstance() {
  _is_default_instance_ = true;
  part_ = const_cast< ::content::ContentPart*>(&::content::ContentPart::default_instance());
}

UpdatePart::UpdatePart(const UpdatePart& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:content.UpdatePart)
}

void UpdatePart::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  part_ = NULL;
  position_ = 0u;
}

UpdatePart::~UpdatePart() {
  // @@protoc_insertion_point(destructor:content.UpdatePart)
  SharedDtor();
}

void UpdatePart::SharedDtor() {
  if (GetArenaNoVirtual() != NULL) {
    return;
  }

  if (this != default_instance_) {
    delete part_;
  }
}

void UpdatePart::ArenaDtor(void* object) {
  UpdatePart* _this = reinterpret_cast< UpdatePart* >(object);
  (void)_this;
}
void UpdatePart::RegisterArenaDtor(::google::protobuf::Arena* arena) {
}
void UpdatePart::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* UpdatePart::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return UpdatePart_descriptor_;
}

const UpdatePart& UpdatePart::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_content_2eproto();
  return *default_instance_;
}

UpdatePart* UpdatePart::default_instance_ = NULL;

UpdatePart* UpdatePart::New(::google::protobuf::Arena* arena) const {
  return ::google::protobuf::Arena::CreateMessage<UpdatePart>(arena);
}

void UpdatePart::Clear() {
  if (GetArenaNoVirtual() == NULL && part_ != NULL) delete part_;
  part_ = NULL;
  position_ = 0u;
}

bool UpdatePart::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:content.UpdatePart)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .content.ContentPart part = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_part()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_position;
        break;
      }

      // optional uint32 position = 2;
      case 2: {
        if (tag == 16) {
         parse_position:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &position_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:content.UpdatePart)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:content.UpdatePart)
  return false;
#undef DO_
}

void UpdatePart::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:content.UpdatePart)
  // optional .content.ContentPart part = 1;
  if (this->has_part()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, *this->part_, output);
  }

  // optional uint32 position = 2;
  if (this->position() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->position(), output);
  }

  // @@protoc_insertion_point(serialize_end:content.UpdatePart)
}

::google::protobuf::uint8* UpdatePart::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:content.UpdatePart)
  // optional .content.ContentPart part = 1;
  if (this->has_part()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, *this->part_, target);
  }

  // optional uint32 position = 2;
  if (this->position() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->position(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:content.UpdatePart)
  return target;
}

int UpdatePart::ByteSize() const {
  int total_size = 0;

  // optional .content.ContentPart part = 1;
  if (this->has_part()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->part_);
  }

  // optional uint32 position = 2;
  if (this->position() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->position());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void UpdatePart::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const UpdatePart* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const UpdatePart>(
          &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void UpdatePart::MergeFrom(const UpdatePart& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from.has_part()) {
    mutable_part()->::content::ContentPart::MergeFrom(from.part());
  }
  if (from.position() != 0) {
    set_position(from.position());
  }
}

void UpdatePart::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void UpdatePart::CopyFrom(const UpdatePart& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool UpdatePart::IsInitialized() const {

  return true;
}

void UpdatePart::Swap(UpdatePart* other) {
  if (other == this) return;
  if (GetArenaNoVirtual() == other->GetArenaNoVirtual()) {
    InternalSwap(other);
  } else {
    UpdatePart temp;
    temp.MergeFrom(*this);
    CopyFrom(*other);
    other->CopyFrom(temp);
  }
}
void UpdatePart::UnsafeArenaSwap(UpdatePart* other) {
  if (other == this) return;
  GOOGLE_DCHECK(GetArenaNoVirtual() == other->GetArenaNoVirtual());
  InternalSwap(other);
}
void UpdatePart::InternalSwap(UpdatePart* other) {
  std::swap(part_, other->part_);
  std::swap(position_, other->position_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata UpdatePart::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = UpdatePart_descriptor_;
  metadata.reflection = UpdatePart_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// UpdatePart

// optional .content.ContentPart part = 1;
bool UpdatePart::has_part() const {
  return !_is_default_instance_ && part_ != NULL;
}
void UpdatePart::clear_part() {
  if (GetArenaNoVirtual() == NULL && part_ != NULL) delete part_;
  part_ = NULL;
}
 const ::content::ContentPart& UpdatePart::part() const {
  // @@protoc_insertion_point(field_get:content.UpdatePart.part)
  return part_ != NULL ? *part_ : *default_instance_->part_;
}
 ::content::ContentPart* UpdatePart::mutable_part() {
  
  if (part_ == NULL) {
    _slow_mutable_part();  }
  // @@protoc_insertion_point(field_mutable:content.UpdatePart.part)
  return part_;
}
 ::content::ContentPart* UpdatePart::release_part() {
  
  if (GetArenaNoVirtual() != NULL) {
    return _slow_release_part();
  } else {
    ::content::ContentPart* temp = part_;
    part_ = NULL;
    return temp;
  }
}
 void UpdatePart::set_allocated_part(::content::ContentPart* part) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete part_;
  }
  if (part != NULL) {
    _slow_set_allocated_part(message_arena, &part);
  }
  part_ = part;
  if (part) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:content.UpdatePart.part)
}

// optional uint32 position = 2;
void UpdatePart::clear_position() {
  position_ = 0u;
}
 ::google::protobuf::uint32 UpdatePart::position() const {
  // @@protoc_insertion_point(field_get:content.UpdatePart.position)
  return position_;
}
 void UpdatePart::set_position(::google::protobuf::uint32 value) {
  
  position_ = value;
  // @@protoc_insertion_point(field_set:content.UpdatePart.position)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace content

// @@protoc_insertion_point(global_scope)
